In [1]:
import numpy as np

In [4]:
a = np.array([[0.9, 0.07, 0.02, 0.01],
              [0, 0.93, 0.05, 0.02],
              [0, 0, 0.85, 0.15],
              [0, 0, 0, 1]])

In [5]:
X = np.array([[0.85, .1, 0.05, 0]])

In [6]:
a.T @ X.T


array([[0.765 ],
       [0.1525],
       [0.0645],
       [0.018 ]])

In [11]:
a.T.shape

(4, 4)

In [9]:
X.T.shape

(4, 1)

In [12]:
(a.T @ X.T).shape

(4, 1)

## Task 2

In [13]:
persons = np.array([[6, 5, 3, 1],
                    [3, 6, 2, 2],
                    [3, 4, 3, 1]])

In [26]:
prices_1 = np.array([[1.5, 2, 5, 16]])

In [17]:
prices_1.T

array([[ 1.5],
       [ 2. ],
       [ 5. ],
       [16. ]])

In [29]:
np.sum(persons @ prices_1.T)

152.0

In [25]:
prices_2 = np.array([[1, 2.5, 4.5, 17]])

In [28]:
np.sum(persons @ prices_2.T)

153.5

### Computational Stability

In [38]:
import scipy.linalg as la

In [39]:
A = np.array([[1, 1000], [0, 1]])
B = np.array([[1, 1000], [0.001, 1]])

In [42]:
np.set_printoptions(suppress=True, 
                    precision=4)

In [45]:
wA, vrA = la.eig(A)
wB, vrB = la.eig(B)

In [47]:
la.eig(A)

(array([1.+0.j, 1.+0.j]),
 array([[ 1., -1.],
        [ 0.,  0.]]))